/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteDonateDetailsRouteImport } from './routes/_site.donate-details'
import { Route as SiteDonateRouteImport } from './routes/_site.donate'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SitePostsIndexRouteImport } from './routes/_site.posts.index'
import { Route as SitePostsSlugRouteImport } from './routes/_site.posts.$slug'
import { Route as SitePagesSlugRouteImport } from './routes/_site.pages.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDonateDetailsRoute = SiteDonateDetailsRouteImport.update({
  id: '/donate-details',
  path: '/donate-details',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDonateRoute = SiteDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SitePostsIndexRoute = SitePostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePostsSlugRoute = SitePostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SitePagesSlugRoute = SitePagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/donate': typeof SiteDonateRoute
  '/donate-details': typeof SiteDonateDetailsRoute
  '/gallery': typeof SiteGalleryRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/pages/$slug': typeof SitePagesSlugRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/posts/': typeof SitePostsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/donate': typeof SiteDonateRoute
  '/donate-details': typeof SiteDonateDetailsRoute
  '/gallery': typeof SiteGalleryRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/pages/$slug': typeof SitePagesSlugRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/posts': typeof SitePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/donate': typeof SiteDonateRoute
  '/_site/donate-details': typeof SiteDonateDetailsRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/team': typeof AdminTeamRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/pages/$slug': typeof SitePagesSlugRoute
  '/_site/posts/$slug': typeof SitePostsSlugRoute
  '/_site/posts/': typeof SitePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/donate'
    | '/donate-details'
    | '/gallery'
    | '/admin/cms'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/team'
    | '/admin/'
    | '/pages/$slug'
    | '/posts/$slug'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/donate'
    | '/donate-details'
    | '/gallery'
    | '/admin/cms'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/team'
    | '/'
    | '/admin'
    | '/pages/$slug'
    | '/posts/$slug'
    | '/posts'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/donate'
    | '/_site/donate-details'
    | '/_site/gallery'
    | '/admin/cms'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/team'
    | '/_site/'
    | '/admin/'
    | '/_site/pages/$slug'
    | '/_site/posts/$slug'
    | '/_site/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/donate-details': {
      id: '/_site/donate-details'
      path: '/donate-details'
      fullPath: '/donate-details'
      preLoaderRoute: typeof SiteDonateDetailsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/donate': {
      id: '/_site/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof SiteDonateRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/posts/': {
      id: '/_site/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof SitePostsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/posts/$slug': {
      id: '/_site/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof SitePostsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pages/$slug': {
      id: '/_site/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof SitePagesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDonateRoute: typeof SiteDonateRoute
  SiteDonateDetailsRoute: typeof SiteDonateDetailsRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePagesSlugRoute: typeof SitePagesSlugRoute
  SitePostsSlugRoute: typeof SitePostsSlugRoute
  SitePostsIndexRoute: typeof SitePostsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDonateRoute: SiteDonateRoute,
  SiteDonateDetailsRoute: SiteDonateDetailsRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePagesSlugRoute: SitePagesSlugRoute,
  SitePostsSlugRoute: SitePostsSlugRoute,
  SitePostsIndexRoute: SitePostsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
